# Form implementation generated from reading ui file '.\buyBook.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(335, 546)
        self.label_result = QtWidgets.QLabel(Dialog)
        self.label_result.setGeometry(QtCore.QRect(20, 360, 301, 61))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(14)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(90, 290, 121, 51))
        font = QtGui.QFont()
        font.setFamily("华文彩云")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(80, 190, 142, 81))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pay_radioButton_ali = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pay_radioButton_ali.setFont(font)
        self.pay_radioButton_ali.setObjectName("pay_radioButton_ali")
        self.verticalLayout_2.addWidget(self.pay_radioButton_ali)
        self.pay_radioButton_wx = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pay_radioButton_wx.setFont(font)
        self.pay_radioButton_wx.setObjectName("pay_radioButton_wx")
        self.verticalLayout_2.addWidget(self.pay_radioButton_wx)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(90, 42, 122, 110))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_py = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(14)
        self.radioButton_py.setFont(font)
        self.radioButton_py.setObjectName("radioButton_py")
        self.verticalLayout.addWidget(self.radioButton_py)
        self.radioButton_java = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(14)
        self.radioButton_java.setFont(font)
        self.radioButton_java.setObjectName("radioButton_java")
        self.verticalLayout.addWidget(self.radioButton_java)
        self.radioButton_js = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(14)
        self.radioButton_js.setFont(font)
        self.radioButton_js.setObjectName("radioButton_js")
        self.verticalLayout.addWidget(self.radioButton_js)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "好的"))
        self.label_2.setText(_translate("Dialog", "请选择付款方式"))
        self.pay_radioButton_ali.setText(_translate("Dialog", "aliPay"))
        self.pay_radioButton_wx.setText(_translate("Dialog", "wxPay"))
        self.label.setText(_translate("Dialog", "选择你的课本"))
        self.radioButton_py.setText(_translate("Dialog", "Python"))
        self.radioButton_java.setText(_translate("Dialog", "Java"))
        self.radioButton_js.setText(_translate("Dialog", "JavaScript"))

        self.pushButton.clicked.connect(self.ok_button)

    def ok_button(self):
        book = '还未选择书籍'
        pay = '还未选择支付方式'
        if self.radioButton_py.isChecked():
            # python书籍被选中了
            book = self.radioButton_py.text()
        elif self.radioButton_java.isChecked():
            book = self.radioButton_java.text()
        elif self.radioButton_js.isChecked():
            book = self.radioButton_js.text()

        if self.pay_radioButton_ali.isChecked():
            pay = '支付宝'
        elif self.pay_radioButton_wx.isChecked():
            pay = '微信'

        self.label_result.setText(f'您选择的书籍是:{book},\n付款方式是:{pay}')


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
