# Form implementation generated from reading ui file '.\ListWidgetApp.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PySide6.QtWidgets import QDialog, QInputDialog, QLineEdit, QMessageBox


class Ui_Form(QDialog):
    def __init__(self):
        super().__init__()
        self.btn_add = None
        self.btn_del = None
        self.update = None
        self.btn_sort = None
        self.horizontalLayout = None
        self.widget = None
        self.listWidget = None

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(348, 326)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(10, 70, 321, 241))
        self.listWidget.setObjectName("listWidget")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 20, 320, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_sort = QtWidgets.QPushButton(self.widget)
        self.btn_sort.setObjectName("btn_sort")
        self.horizontalLayout.addWidget(self.btn_sort)
        self.update = QtWidgets.QPushButton(self.widget)
        self.update.setObjectName("update")
        self.horizontalLayout.addWidget(self.update)
        self.btn_del = QtWidgets.QPushButton(self.widget)
        self.btn_del.setObjectName("btn_del")
        self.horizontalLayout.addWidget(self.btn_del)
        self.btn_add = QtWidgets.QPushButton(self.widget)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ListWidgetApp"))
        self.btn_sort.setText(_translate("Form", "排序"))
        self.update.setText(_translate("Form", "修改"))
        self.btn_del.setText(_translate("Form", "删除"))
        self.btn_add.setText(_translate("Form", "添加"))
        self.btn_add.clicked.connect(self.add_item)
        self.btn_del.clicked.connect(self.del_item)
        self.update.clicked.connect(self.edit_item)
        self.btn_sort.clicked.connect(self.sort_item)

    def add_item(self):
        row = self.listWidget.currentRow()
        title = "add Item"
        data, ok = QInputDialog.getText(self, title, None)
        if ok and data is not None:
            self.listWidget.insertItem(row, data)

    def del_item(self):
        row = self.listWidget.currentRow()
        item = self.listWidget.item(row)
        # 判断元素是否为空
        if item is None:
            return None
        reply = QMessageBox.question(self, "要删除吗", " 你要删除这个元素?",
                                     QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No)

        if reply == QMessageBox.StandardButton.Yes:
            self.listWidget.takeItem(row)

    def sort_item(self):
        self.listWidget.sortItems()

    def edit_item(self):
        # 找到当前行
        row = self.listWidget.currentRow()
        # 获取当前元素
        item = self.listWidget.item(row)
        # 判断元素是否为空
        if item is not None:
            # 给弹出框一个标题
            title = "edit Item"
            data, ok = QInputDialog.getText(self, title, title, QLineEdit.EchoMode.Normal, item.text())
            if ok and data is not None:
                item.setText(data)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
