# Form implementation generated from reading ui file '.\QDialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog


class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(411, 160)
        Dialog.setStyleSheet("QDialog\n"
                             "{\n"
                             "background-color: rgb(255, 255, 191)\n"
                             "}\n"
                             "")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.shenxinfu = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        self.shenxinfu.setFont(font)
        self.shenxinfu.setObjectName("shenxinfu")
        self.verticalLayout.addWidget(self.shenxinfu)
        self.youren = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        font.setBold(False)
        self.youren.setFont(font)
        self.youren.setStyleSheet("")
        self.youren.setObjectName("youren")
        self.verticalLayout.addWidget(self.youren)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "选择创建对象"))
        self.shenxinfu.setText(_translate("Dialog", "深信服"))
        self.youren.setText(_translate("Dialog", "有人物联网路由器"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
