# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QIntValidator


class Ui_GuoShun(object):
    def setupUi(self, GuoShun):
        GuoShun.setObjectName("GuoShun")
        GuoShun.setWindowModality(QtCore.Qt.WindowModal)
        GuoShun.resize(1080, 500)
        GuoShun.setLayoutDirection(QtCore.Qt.LeftToRight)
        GuoShun.setAutoFillBackground(True)

        self.startButton = QtWidgets.QPushButton(GuoShun)
        self.startButton.setGeometry(QtCore.QRect(470, 30, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(24)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.label_status = QtWidgets.QLabel(GuoShun)
        self.label_status.setGeometry(QtCore.QRect(20, 110, 181, 51))

        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(20)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.tableWidget = QtWidgets.QTableWidget(GuoShun)
        self.tableWidget.setGeometry(QtCore.QRect(10, 300, 931, 171))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.label_time = QtWidgets.QLabel(GuoShun)
        self.label_time.setGeometry(QtCore.QRect(20, 190, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")

        self.lineEdit = QtWidgets.QLineEdit(GuoShun)
        self.lineEdit.setGeometry(QtCore.QRect(310, 30, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setFixedWidth(100)
        self.lineEdit.setObjectName("lineEdit")
        self.label_status_2 = QtWidgets.QLabel(GuoShun)
        self.label_status_2.setGeometry(QtCore.QRect(20, 20, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(20)
        self.label_status_2.setFont(font)
        self.label_status_2.setObjectName("label_status_2")

        self.retranslateUi(GuoShun)
        QtCore.QMetaObject.connectSlotsByName(GuoShun)

    def retranslateUi(self, GuoShun):
        _translate = QtCore.QCoreApplication.translate
        GuoShun.setWindowTitle(_translate("GuoShun", "国舜流量工具"))
        self.startButton.setText(_translate("GuoShun", "开始"))
        self.label_status.setText(_translate("GuoShun", "当前状态:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("GuoShun", "项目名称", "projectName"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("GuoShun", "当前ip", "dedicatedIP"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("GuoShun", "链接名称", "vpnConnName"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("GuoShun", "网络状态", "networkStatus"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("GuoShun", "速率[Kbps] - 负载百分比%"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("GuoShun", "数据来源", "dataSource"))
        self.label_time.setText(_translate("GuoShun", "最后一次更新时间:"))
        self.label_status_2.setText(_translate("GuoShun", "上传频率设置(秒):"))
        self.lineEdit.setText(str(2))

        # 整数校验器 [1,99]
        intValidator = QIntValidator()
        intValidator.setRange(1, 3600)
        self.lineEdit.setValidator(intValidator)

        self.tableWidget.setFixedWidth(1055)
        self.tableWidget.setColumnWidth(1, 280)
        self.tableWidget.setColumnWidth(4, 280)
        self.tableWidget.setColumnWidth(5, 178)


class Dialog(QtWidgets.QDialog, QtWidgets.QWidget):
    """对QDialog类重写，实现一些功能"""

    def closeEvent(self, event):
        """
        重写closeEvent方法，实现dialog窗体关闭时执行一些代码
        :param event: close()触发的事件
        :return: None
        """
        reply = QtWidgets.QMessageBox.question(self,
                                               '本程序',
                                               "是否要退出程序？",
                                               QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
                                               QtWidgets.QMessageBox.No)
        if reply == QtWidgets.QMessageBox.Yes:
            event.accept()
        else:
            event.ignore()

    def keyPressEvent(self, a0: QtGui.QKeyEvent) -> None:
        # 举例，这里Qt.Key_A注意虽然字母大写，但按键事件对大小写不敏感
        if a0.key() == Qt.Key_Escape:
            self.hide()

    def changeEvent(self, e):
        if e.type() == QtCore.QEvent.WindowStateChange:
            if self.isMinimized():
                self.hide()
            elif self.isMaximized():
                # print("窗口最大化")
                pass
            elif self.isFullScreen():
                # print("全屏显示")
                pass
            elif self.isActiveWindow():
                # print("活动窗口")
                pass
