# -*- coding: utf-8 -*-
import os
import sys

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GuoShun():
    def setupUi(self, GuoShun):
        GuoShun.setObjectName("GuoShun")
        GuoShun.setWindowModality(QtCore.Qt.WindowModal)
        GuoShun.resize(287, 182)
        GuoShun.setLayoutDirection(QtCore.Qt.LeftToRight)
        GuoShun.setAutoFillBackground(True)
        self.startButton = QtWidgets.QPushButton(GuoShun)
        self.startButton.setGeometry(QtCore.QRect(10, 10, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(24)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.label = QtWidgets.QLabel(GuoShun)
        self.label.setGeometry(QtCore.QRect(20, 90, 148, 46))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_status = QtWidgets.QLabel(GuoShun)
        self.label_status.setGeometry(QtCore.QRect(170, 90, 244, 46))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(24)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")

        self.retranslateUi(GuoShun)
        QtCore.QMetaObject.connectSlotsByName(GuoShun)

    def retranslateUi(self, GuoShun):
        _translate = QtCore.QCoreApplication.translate
        GuoShun.setWindowTitle(_translate("GuoShun", "深信服流量爬取"))
        self.startButton.setText(_translate("GuoShun", "开始"))
        self.label.setText(_translate("GuoShun", "当前状态:"))
        self.label_status.setText(_translate("GuoShun", "未启动"))

